### ISSUE TITLE
Input Table with RA/DEC offsets not working/Only works with SEP/PA

### ISSUE THREAD

**Issue by JunellieGnzlz** [sblunt/orbitize#108] opened 2019-06-05 18:36 UTC
I've been working with orbitize now for a couple of weeks (great tool!), and I wanted to raise an issue that came up when inputting the data to orbitize. When trying to read an input table with RA and DEC offsets, a couple of things happened:

1. After reading in the table with RA and DEC offsets successfully with the orbitize.driver.Driver, it prints out "Converting ra/dec data points in data_table to sep/pa. Original data are stored in input_table." But when you print out the data table with myDriver.system.data_table, it prints out the original RA and DEC offsets, instead of printing out the table with the converted values to sep/pa as stated in the statement. There's no sign that it was actually converted.

2. When I try to run the run_sampler for OFTI with the input table containing RA/DEC, it runs forever. It actually doesn't stop running. It doesn't even show the "x/1000 orbits found" progress statement. 

NOTE: When I tried converting the values myself from RA/DEC to SEP/PA using the equations in the orbitize source code and inputting it as a SEP/PA table, it ran smoothly. No issues there, which makes me believe there is some sort of bug when inputting the RA/DEC tables where it doesn't convert the values and doesn't let the sampler run as it should.

**Comment by henry-ngo** [comment] 2019-06-05 22:56
Hi @JunellieGnzlz ! Thanks for the report. I'll check this out. I just recently did something similar but I read the input table directly with the `read_input` module. So it might be something in `Driver` that is causing the issue(s).

**Comment by sblunt** [comment] 2019-06-05 22:58
Thanks for using orbitize, @JunellieGnzlz! And thanks for handling this bug, @henry-ngo!

**Comment by henry-ngo** [comment] 2019-06-06 18:09
Hi @sblunt , @logan-pearce and @isabelangelo:

I think I found the cause of the issue! Context, in case you find a reminder useful: We recently changed the behaviour of the OFTI sampler when it is given ra/dec as input (as @JunellieGnzlz has done) so that we save the actual input as an attribute of the `sampler` object (i.e. `sampler.input_table`) instead of simply overwriting the old line in `data_table`. 

However, there is some confusion here because it turns out we have been saving `data_table` in two places when it comes to the OFTI sampler. We have `system.data_table` as well as `sampler.data_table`. In the OFTI class definition, our`__init__` call checks if input is given in ra/dec and converts it to sep/pa, and stores it as **`sampler`**`.data_table`. The OFTI class does not have its own `_logL` function definition, instead it just inherits it from the base class. But when we look at the `_logL` function from the base class, it uses **`system`**`.data_table`.

Here are some convenient links to the relevant lines of code:
`__init__` function for OFTI class: https://github.com/sblunt/orbitize/blob/997647cc3559f7968a370334d8d067aebe349100/orbitize/sampler.py#L99 (I think Lines 109-110 are showing that we create `input_table` and a copy of `data_table` from `system` in `sampler`).
`_logL` function from the base `sampler` class: https://github.com/sblunt/orbitize/blob/997647cc3559f7968a370334d8d067aebe349100/orbitize/sampler.py#L46 (Lines 66-67 show that we are passing in parameters from `system` not `sampler` (`self`). 

I think this explains the second problem reported here. We do convert the input values but we don't use the converted values for the likelihood estimation, so then the `OFTI` class doesn't compute correct likelihoods and rejects everything, so no progress is made. This is also consistent with when @JunellieGnzlz converted to sep/pa manually, there is no problem. 

Before I suggest a solution, I want to point out another related potential issue (which explains the first item in this report, i.e. even `system.data_table` is not updated to have sep/pa). In Lines 119-128 of `sampler.py`'s `__init__` function (see link above for the `__init__` function), we do the conversion. However, we just store the converted results as `sampler.sep_observed`, `sampler.sep_err`, `sampler.pa_observed`, and `sampler.pa_err`. These values were originally copied from `data_table` but we don't propagate these changes back to `data_table`. I checked this too---when I print `sampler.sep_observed` directly, I do get the converted value (but not when I print `sampler.data_table`). 

**Suggested Changes**
I originally signed up for the bug issue since I thought it was an error in `read_input.py` but this will mostly require changes in the OFTI part of `sampler.py` which I have less experience with! So I think we should discuss the plan before I implement anything. We also need to be careful not to break the MCMC sampler.

Ultimately, I think the two things we need to fix are:
1. Resolve the conflict between having both `sampler.data_table` and `system.data_table` and use the correct `data_table` for the calculation of logL in OFTI. 
2. Propagate radec-->seppa conversions to `sampler/system.data_table`

For (1), I believe that if we just decide to use `system.data_table` instead of a copy within `sampler` then this would solve this whole issue. 

To resolve the conflict in repeated names, I propose we eliminate the use of `sampler.input_table` and 'sampler.data_table` in favour of `system.input_table` and `system.data_table`. This will keep things consistent with the MCMC sampler and I think it fits better with our overall design of having system-wide info in `system`. But if others feel strongly about accessing this thru `sampler`, maybe there is a way to link the two thru assignment by reference or something so that a change in one will change the other?

For (2), I think this is straight-forward to do once we decide how to resolve the double names above. The OFTI sampler itself uses a copy of values from `data_table` and we can keep that (especially if it's faster) but we should ensure the copying is done **after** the unit conversions.

How does those sound? Any problems I didn't forsee? If it sounds good, let me know and I'll make a branch and a PR for the OFTI experts to inspect to ensure I didn't break anything :)

**Comment by sblunt** [comment] 2019-06-06 20:54
Hey @henry-ngo ! Thanks for the detailed report. I agree with you that it makes the most sense to just eliminate the `sampler.data_table` object. Let me know if you run into any issues implementing this fix.

**Comment by semaphoreP** [comment] 2019-06-06 20:58
Excellent in depth debugging! Yeah, I agree that having multiple data_tables causes confusion like this bug we ran into. Let's keep it all in the system class like you suggested. I'm happy to double check that it won't affect the MCMC sampler.

**Comment by sblunt** [comment] 2019-06-10 17:45
Addressed in PR #109. Thanks again @JunellieGnzlz @henry-ngo!

**Closed by sblunt** 2019-06-10 17:45 UTC
Labels: bug
