### ISSUE TITLE
load_results bug with hipparcos iad fits

### ISSUE THREAD

**Issue by rbowru** [sblunt/orbitize#315] opened 2022-03-31 21:28 UTC
When I attempt to use load_results to open a .hdf5 file that was made from a fit that included hipparcos/gaia astrometry, I get an error that says "ValueError: could not convert string to float."   I've included the full output in a screenshot: 
![Screen Shot 2022-03-31 at 2 26 01 PM](https://user-images.githubusercontent.com/66432460/161151961-d5c79869-823f-4e40-9f3c-a6f7233a9309.png)
 
Thanks!

**Comment by sblunt** [comment] 2022-04-22 00:13
Hey Rachel, thanks for raising this issue! I couldn't reproduce this error-- check out tests/test_hipparcos.py unit test I just added (`test_save_load()`)

Do you have the most updated version of orbitize? If so, can you share the code you're using to save the results object?

**Comment by sblunt** [comment] 2022-04-22 00:30
Oh, one thought-- are you defining the Gaia dr number as a string?

**Comment by rbowru** [comment] 2022-04-25 20:22
Oh, good catch!  I was not defining the edr3 number as a string!    When I have a good break in the simulations that I'm trying to run, I'll make sure this solved the problem.  Thank you!

**Comment by sblunt** [comment] 2022-05-13 23:30
@rbowru did this fix work?

**Comment by sblunt** [comment] 2022-05-24 23:41
Closing, feel free to reopen if needed.

**Closed by sblunt** 2022-05-24 23:41 UTC
