### ISSUE TITLE
Running the MCMC sampler iteratively seems to increase runtime?

### ISSUE THREAD

**Issue by vighnesh-nagpal** [sblunt/orbitize#188] opened 2020-10-22 04:14 UTC
For a given number of total steps, it appears that running the MCMC sampler iteratively drastically drives up runtime as compared to executing the run in one go.  For MCMC runs of 10000 steps using the same test data, the iterative run only takes around 2000 steps in the time it takes for the non-iterative run to finish its 10000 steps. 

I set up the iterations similar to the way it's documented in the Radial Velocity MCMC tutorial on the docs (code below). 

```
n_iter = 5 # number of iterations
for i in range(n_iter):
    # running the sampler:
    orbits = m.run_sampler(total_orbits, burn_steps=0, thin=1)
```

**Comment by semaphoreP** [comment] 2020-11-18 20:55
We want a way to stop and resume MCMC runs for the case of long MCMC runs. Duplicate of #104

**Closed by semaphoreP** 2020-11-18 20:55 UTC
