### ISSUE TITLE
Value Error when specifying starting epoch for plots

### ISSUE THREAD

**Issue by JunellieGnzlz** [sblunt/orbitize#148] opened 2019-11-11 19:04 UTC
Whenever I try to plot the orbits which includes “start_mjd=epochs[0]", the snippet of code below is in the tutorial notebook:

epochs = myDriver.system.data_table['epoch']
orbit_figure = myResults.plot_orbits(
    start_mjd=epochs[0] # Minimum MJD for colorbar (here we choose first data epoch)
    )

It gives me the following error:

"ValueError: x and y must have same first dimension, but have shapes (1,) and (100,)"

When I comment out the start_mjd line, the plot appears fine without any errors, but if I want to specify the starting epoch, I can't. Not even if I write in the epoch number instead of using the epochs array.

**Comment by sblunt** [comment] 2019-11-15 00:50
Hey Junellie,

Thanks for the bug report! 

I'm unable to reproduce this error running the OFTI tutorial notebook on my machine. Is that the notebook you're having trouble with? Note that in that tutorial, `epochs` is defined in the same cell.

**Comment by sblunt** [comment] 2020-01-28 03:57
Addressed in PR #149

**Closed by sblunt** 2020-01-28 03:57 UTC
Labels: bug
