### ISSUE TITLE
PyCharm + OFTI = Bug ? 

### ISSUE THREAD

**Issue by sylacour** [sblunt/orbitize#167] opened 2020-04-29 16:28 UTC
Hello

I am running the OFTI script in:
http://orbitize.info/en/latest/tutorials/Quick-Start.html
under PyCharm (v2020.1), but I get the following error messages. However,
- It works if I run the same script in Spyder.
- It works if I run the fit with MCMC in PyCharm.
So it looks like something deep within PyCharm of OFTI.
Thanks for the tool!

Sylvestre

0/1 orbits foundProcess Process-5:
Process Process-2:
Process Process-3:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/slacour/opt/anaconda3/lib/python3.7/multiprocessing/managers.py", line 811, in _callmethod
    conn = self._tls.connection
  File "/Users/slacour/opt/anaconda3/lib/python3.7/multiprocessing/managers.py", line 811, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'
During handling of the above exception, another exception occurred:
  File "/Users/slacour/opt/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/Users/slacour/opt/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/slacour/opt/anaconda3/lib/python3.7/site-packages/orbitize/sampler.py", line 361, in _sampler_process
    output.put((np.array(output_orbits), output_lnlikes))
  File "<string>", line 2, in put
  File "/Users/slacour/opt/anaconda3/lib/python3.7/multiprocessing/managers.py", line 815, in _callmethod
    self._connect()
  File "/Users/slacour/opt/anaconda3/lib/python3.7/multiprocessing/managers.py", line 802, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/Users/slacour/opt/anaconda3/lib/python3.7/multiprocessing/connection.py", line 492, in Client
    c = SocketClient(address)
Traceback (most recent call last):
  File "/Users/slacour/opt/anaconda3/lib/python3.7/multiprocessing/connection.py", line 619, in SocketClient
    s.connect(address)
  File "/Users/slacour/opt/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/slacour/opt/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/slacour/opt/anaconda3/lib/python3.7/site-packages/orbitize/sampler.py", line 361, in _sampler_process
    output.put((np.array(output_orbits), output_lnlikes))
  File "<string>", line 2, in put
  File "/Users/slacour/opt/anaconda3/lib/python3.7/multiprocessing/managers.py", line 815, in _callmethod
    self._connect()
  File "/Users/slacour/opt/anaconda3/lib/python3.7/multiprocessing/managers.py", line 802, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
ConnectionRefusedError: [Errno 61] Connection refused
  File "/Users/slacour/opt/anaconda3/lib/python3.7/multiprocessing/managers.py", line 811, in _callmethod
    conn = self._tls.connection
  File "/Users/slacour/opt/anaconda3/lib/python3.7/multiprocessing/connection.py", line 498, in Client
    answer_challenge(c, authkey)
  File "/Users/slacour/opt/anaconda3/lib/python3.7/multiprocessing/connection.py", line 741, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/Users/slacour/opt/anaconda3/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/Users/slacour/opt/anaconda3/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/Users/slacour/opt/anaconda3/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'
EOFError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/slacour/opt/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/slacour/opt/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/slacour/opt/anaconda3/lib/python3.7/site-packages/orbitize/sampler.py", line 361, in _sampler_process
    output.put((np.array(output_orbits), output_lnlikes))
  File "<string>", line 2, in put
  File "/Users/slacour/opt/anaconda3/lib/python3.7/multiprocessing/managers.py", line 815, in _callmethod
    self._connect()
  File "/Users/slacour/opt/anaconda3/lib/python3.7/multiprocessing/managers.py", line 802, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/Users/slacour/opt/anaconda3/lib/python3.7/multiprocessing/connection.py", line 492, in Client
    c = SocketClient(address)
  File "/Users/slacour/opt/anaconda3/lib/python3.7/multiprocessing/connection.py", line 619, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 61] Connection refused

**Comment by sblunt** [comment] 2020-04-29 19:21
Hey Sylvestre, thanks for the bug report! I just tried running the quickstart script in PyCharm, and I wasn't able to reproduce the bug. (I don't usually use PyCharm, so it's totally possible I'm doing something strange). It looks like the error has to do with OFTI's multiprocessing. Could you try running the following simple multiprocessing script (taken from the multiprocessing docs page)? 

What version of `multiprocessing` do you have installed?

```
from multiprocessing import Process
import os

def info(title):
    print title
    print 'module name:', __name__
    if hasattr(os, 'getppid'):  # only available on Unix
        print 'parent process:', os.getppid()
    print 'process id:', os.getpid()

def f(name):
    info('function f')
    print 'hello', name

if __name__ == '__main__':
    info('main line')
    p = Process(target=f, args=('bob',))
    p.start()
    p.join()
```

**Comment by sylacour** [comment] 2020-04-29 19:47
Hello Sarah

The script was python 2, but after changing the print, it worked. 
Here what I got:

main line
module name: __main__
parent process: 979
process id: 4119
function f
module name: __main__
parent process: 4119
process id: 4122
hello bob


The exact template I used (which failed) is this one:


Does it work on your computer?

S.

**Comment by sblunt** [comment] 2020-04-30 20:11
Ah, sorry about the Python2/3 conversion (I just copied it from the `multiprocessing` docs page). It's good that it's working though. 

Yes, the orbitize! quickstart script is working on my computer in PyCharm v2020.1 (same as yours). Let's try to pin down what else might be different between our setups:

- Type `pip list` into a terminal and let me know what it says (I want to make sure I have all the same relevant package versions as you). 
- Let me know what type of OS you have.

**Comment by sylacour** [comment] 2020-05-04 08:04
Hello Sarah

I have OS Catalina (v10.15.4).

Here are my pip list

Package                            Version     Location                                   
---------------------------------- ----------- -------------------------------------------
-rbitize                           1.11.0      
alabaster                          0.7.12      
anaconda-client                    1.7.2       
anaconda-navigator                 1.9.7       
anaconda-project                   0.8.3       
appnope                            0.1.0       
appscript                          1.0.1       
asn1crypto                         1.0.1       
astroid                            2.3.1       
astropy                            4.0.1.post1 
atomicwrites                       1.3.0       
attrs                              19.2.0      
Babel                              2.7.0       
backcall                           0.1.0       
backports.functools-lru-cache      1.5         
backports.os                       0.1.1       
backports.shutil-get-terminal-size 1.0.0       
backports.tempfile                 1.0         
backports.weakref                  1.0.post1   
beautifulsoup4                     4.8.0       
bitarray                           1.0.1       
bkcharts                           0.2         
bleach                             3.1.0       
bokeh                              1.3.4       
boto                               2.49.0      
Bottleneck                         1.2.1       
certifi                            2019.9.11   
cffi                               1.12.3      
chardet                            3.0.4       
Click                              7.0         
cloudpickle                        1.2.2       
clyent                             1.2.2       
colorama                           0.4.1       
conda                              4.7.12      
conda-build                        3.18.9      
conda-package-handling             1.6.0       
conda-verify                       3.4.2       
contextlib2                        0.6.0       
corner                             2.0.1       
cryptography                       2.7         
cycler                             0.10.0      
Cython                             0.29.13     
cytoolz                            0.10.0      
dask                               2.5.2       
decorator                          4.4.0       
defusedxml                         0.6.0       
deprecation                        2.1.0       
distributed                        2.5.2       
docutils                           0.15.2      
emcee                              2.2.1       
entrypoints                        0.3         
et-xmlfile                         1.0.1       
fastcache                          1.1.0       
filelock                           3.0.12      
Flask                              1.1.1       
fsspec                             0.5.2       
future                             0.17.1      
gevent                             1.4.0       
glob2                              0.7         
gmpy2                              2.0.8       
greenlet                           0.4.15      
h5py                               2.9.0       
HeapDict                           1.0.1       
html5lib                           1.0.1       
idna                               2.8         
imageio                            2.6.0       
imagesize                          1.1.0       
importlib-metadata                 0.23        
ipykernel                          5.1.4       
ipython                            7.8.0       
ipython-genutils                   0.2.0       
ipywidgets                         7.5.1       
isort                              4.3.21      
itsdangerous                       1.1.0       
jdcal                              1.4.1       
jedi                               0.15.1      
Jinja2                             2.10.3      
joblib                             0.13.2      
json5                              0.8.5       
jsonschema                         3.0.2       
jupyter                            1.0.0       
jupyter-client                     5.3.3       
jupyter-console                    6.0.0       
jupyter-core                       4.5.0       
jupyterlab                         1.1.4       
jupyterlab-server                  1.0.6       
keyring                            18.0.0      
kiwisolver                         1.1.0       
lazy-object-proxy                  1.4.2       
libarchive-c                       2.8         
lief                               0.9.0       
llvmlite                           0.29.0      
locket                             0.2.0       
lxml                               4.4.1       
MarkupSafe                         1.1.1       
matplotlib                         3.1.1       
mccabe                             0.6.1       
mistune                            0.8.4       
mkl-fft                            1.0.14      
mkl-random                         1.1.0       
mkl-service                        2.3.0       
mock                               3.0.5       
more-itertools                     7.2.0       
mpmath                             1.1.0       
msgpack                            0.6.1       
multipledispatch                   0.6.0       
navigator-updater                  0.2.1       
nbconvert                          5.6.0       
nbformat                           4.4.0       
networkx                           2.3         
nltk                               3.4.5       
nose                               1.3.7       
notebook                           6.0.1       
numba                              0.45.1      
numexpr                            2.7.0       
numpy                              1.17.2      
numpydoc                           0.9.1       
olefile                            0.46        
openpyxl                           3.0.0       
orbitize                           1.11.0      /Users/slacour/ONGOING/GitsVarious/orbitize
packaging                          19.2        
pandas                             0.25.1      
pandocfilters                      1.4.2       
parso                              0.5.1       
partd                              1.0.0       
path.py                            12.0.1      
pathlib2                           2.3.5       
patsy                              0.5.1       
pep8                               1.7.1       
pexpect                            4.7.0       
pickleshare                        0.7.5       
Pillow                             6.2.0       
pip                                19.2.3      
pkginfo                            1.5.0.1     
pluggy                             0.13.0      
ply                                3.11        
prometheus-client                  0.7.1       
prompt-toolkit                     2.0.10      
psutil                             5.6.3       
ptemcee                            1.0.0       
ptyprocess                         0.6.0       
py                                 1.8.0       
pycodestyle                        2.5.0       
pycosat                            0.6.3       
pycparser                          2.19        
pycrypto                           2.6.1       
pycurl                             7.43.0.3    
pyflakes                           2.1.1       
Pygments                           2.4.2       
pylint                             2.4.2       
pyodbc                             4.0.27      
pyOpenSSL                          19.0.0      
pyparsing                          2.4.2       
pyrsistent                         0.15.4      
PySocks                            1.7.1       
pytest                             5.2.1       
pytest-arraydiff                   0.3         
pytest-astropy                     0.5.0       
pytest-doctestplus                 0.4.0       
pytest-openfiles                   0.4.0       
pytest-remotedata                  0.3.2       
python-dateutil                    2.8.0       
pytz                               2019.3      
PyWavelets                         1.0.3       
PyYAML                             5.1.2       
pyzmq                              18.1.0      
QtAwesome                          0.6.0       
qtconsole                          4.5.5       
QtPy                               1.9.0       
requests                           2.22.0      
rope                               0.14.0      
ruamel-yaml                        0.15.46     
scikit-image                       0.15.0      
scikit-learn                       0.21.3      
scipy                              1.3.1       
seaborn                            0.9.0       
Send2Trash                         1.5.0       
setuptools                         41.4.0      
simplegeneric                      0.8.1       
singledispatch                     3.4.0.3     
six                                1.12.0      
snowballstemmer                    2.0.0       
sortedcollections                  1.1.2       
sortedcontainers                   2.1.0       
soupsieve                          1.9.3       
Sphinx                             2.2.0       
sphinxcontrib-applehelp            1.0.1       
sphinxcontrib-devhelp              1.0.1       
sphinxcontrib-htmlhelp             1.0.2       
sphinxcontrib-jsmath               1.0.1       
sphinxcontrib-qthelp               1.0.2       
sphinxcontrib-serializinghtml      1.1.3       
sphinxcontrib-websupport           1.1.2       
spyder                             3.3.6       
spyder-kernels                     0.5.2       
SQLAlchemy                         1.3.9       
statsmodels                        0.10.1      
sympy                              1.4         
tables                             3.5.2       
tblib                              1.4.0       
terminado                          0.8.2       
testpath                           0.4.2       
toolz                              0.10.0      
tornado                            6.0.3       
tqdm                               4.36.1      
traitlets                          4.3.3       
unicodecsv                         0.14.1      
urllib3                            1.24.2      
wcwidth                            0.1.7       
webencodings                       0.5.1       
Werkzeug                           0.16.0      
wheel                              0.33.6      
widgetsnbextension                 3.5.1       
wrapt                              1.11.2      
wurlitzer                          1.0.3       
xlrd                               1.2.0       
XlsxWriter                         1.2.1       
xlwings                            0.15.10     
xlwt                               1.3.0       
zict                               1.0.0       
zipp                               0.6.0       

I am running MCMC now only, and it works fine, so there is no hurry!

Cheers,
Sylvestre

**Comment by sblunt** [comment] 2020-05-07 01:42
Hey Sylvestre,

Everything's still working on my computer even with the same Python package versions as you. I have OSX 10.15.2 so it's possible something weird is going on with a 15.2->15.4 upgrade, but I doubt it.

The next thing I can think to test is whether some of the fancier parallel processing tools we use for OFTI are working on your setup. Can you try running some of the code snippets at [this link](https://pymotw.com/2/multiprocessing/communication.html)? Specifically, I want to test that `multiprocessing .Queue` objects and `multiprocessing.Lock` objects are working on your machine, since OFTI failed on your computer when it tried to add accepted orbits to the `multiprocessing .Queue` object that stores results.

**Comment by sblunt** [comment] 2020-05-14 01:14
See comment [here](https://github.com/sblunt/orbitize/issues/168#issuecomment-628002723) (accidentally posted on wrong issue).

Ok, it looks like it's something wrong with your PyCharm environment, possibly with PyCharm itself. You're having problems with some features of `multiprocessing` that we use in `orbitize!` You could consider contacting the PyCharm folks and asking them what might be going wrong.

Until recently, I did all of my coding using sublime text, but I've switched to VS Code, and I'm very happy with it! If you're looking for an alternative to PyCharm, I can enthusiastically recommend it.

**Comment by sblunt** [comment] 2020-07-04 07:27
Closing because we reached the limit of my ability to help.

**Closed by sblunt** 2020-07-04 07:27 UTC
Labels: bug
