### ISSUE TITLE
new version of emcee

### ISSUE THREAD

**Issue by zhexingli** [sblunt/orbitize#184] opened 2020-08-17 21:13 UTC
Hello, I just noticed that orbitize uses the 2.x version of emcee. Is it possible to upgrade it to the newer 3.x version? Is orbitize compatible with it? Other programs such as radvel uses the 3.x version of emcee and installing orbitize automatically replaces the new version with the old one, which is quite inconvenient :(

**Comment by sblunt** [comment] 2020-08-20 02:45
Duplicate of #141. I'll work on addressing this later this week.

**Closed** 2020-08-20 02:45 UTC
Labels: duplicate

**Comment by sblunt** [comment] 2020-08-28 21:00
Addressed in PR #185.
