### ISSUE TITLE
Raised Error when using RV data

### ISSUE THREAD

**Issue by juague135** [sblunt/orbitize#351] opened 2023-12-15 20:19 UTC
Orbitize raises an exception when attempting to use a dataset with RV data. "Exception:  If including RV data in orbit fit, set fit_secondary_mass=True"

**Comment by semaphoreP** [comment] 2023-12-15 20:21
Note that this is the case of only planetary RV

**Comment by sblunt** [comment] 2024-03-18 22:08
Hey Juan, finally getting around to addressing this bug! I think in the meantime, I must have fixed this somewhere along the line, because I can't reproduce it any more. I was fiddling with the companion rv implementation a lot around this time, so I'm sure it's buried somewhere in all the commit messages. I added a unit test to check this scenario and make sure it stays fixed in the future (in #363). Please reopen if you run into this issue again!

**Closed by sblunt** 2024-03-18 22:08 UTC
Labels: bug
