### ISSUE TITLE
RV Plotting adds Gamma twice?

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#316] opened 2022-04-06 23:02 UTC
**Describe the bug**
I think the gamma offset is corrected for twice in the `plot_orbits` function. 

**To Reproduce**
Run RV Tutorial notebook (the one for HD 4747) and the plot_orbits output is offset from the data. See last figure of tutorial: https://orbitize.readthedocs.io/en/latest/tutorials/RV_MCMC_Tutorial.html

**Expected behavior**
The RV points should line up with the model

**Screenshots**
These look like duplicate lines
https://github.com/sblunt/orbitize/blob/76ced1f124cd5b3ad67e8558217eb90a091a3032/orbitize/plot.py#L554-L555

**Desktop (please complete the following information):**
 - OS: ubuntu
 - orbitize! Version [2.0.0]

**Additional context**

**Comment by sblunt** [comment] 2022-04-22 20:47
Addressed in PR #318. Duplicate of Issue #309.

**Closed by sblunt** 2022-04-22 20:47 UTC
Labels: bug, duplicate
