### ISSUE TITLE
Periodic saving causes parallelized MCMC to slow to a crawl

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#247] opened 2021-07-29 23:06 UTC
Reported by Adam Smith, and I also noticed it this week having not used the feature in a while. Essentially what happens is that we run parallelized MCMC, but after it hits the first periodic save, the MCMC somehow only runs on a single process even though we still have a process pool created. Unclear if something is crashing or all the computations get put onto a single process.

**Comment by semaphoreP** [comment] 2021-12-15 20:43
We should check if it still exists in the newest version of Python.

**Comment by sblunt** [comment] 2021-12-16 20:04
I just checked and couldn't reproduce this behavior on my mac or linux machines (in python3.8). All cores are firing as expected after saving, and the periodic saving seems to work as expected. @semaphoreP @adj-smith could you check if you're still having this issue?

**Comment by sblunt** [comment] 2021-12-16 20:05
I'm using ptemcee for these tests, btw

**Comment by sblunt** [comment] 2022-01-25 00:20
Any updates on this?

**Comment by sblunt** [comment] 2022-05-24 23:42
Closing, reopen if needed.

**Closed by sblunt** 2022-05-24 23:42 UTC
Labels: bug
